version: '3.1'

volumes:
  local_postgres_data: {}

services:
  postgres:
      build:
        context: .
        dockerfile: Dockerfile
      image: queries-postgres
      ports:
        - "5556:5432"
      volumes:
        - local_postgres_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=secretpass
      command:
        # config based on https://www.postgresql.org/docs/current/populate.html
        - "postgres"
#        - "-c"
#        - "log_statement=all"
        - "-c"
        - "shared_buffers=512MB"
        - "-c"
        - "maintenance_work_mem=64MB"
        - "-c"
        - "max_wal_size=2GB"
        - "-c"
        - "archive_mode=off"
        - "-c"
        - "max_wal_senders=0"
