# Generated by Django 3.0.5 on 2020-05-02 17:44

from django.db import migrations


def create_users(apps, schema_editor):
    from django.contrib.auth.models import User  # we want methods from User, so we need to import the actual model
    # UserModel = apps.get_model('auth', 'User')
    for i in range(30):
        User.objects.create_user(f'user{i}', f'user{i}@example.com', '***')


def delete_users(apps, schema_editor):
    UserModel = apps.get_model('auth', 'User')
    UserModel.objects.filter(email__endswith='@example.com').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(create_users, delete_users),
    ]
