# Generated by Django 3.0.5 on 2020-05-02 17:44

from django.db import migrations

USERS = [
    {
        'username': 'john.doe',
        'email': 'john.doe@example.com',
        'password': '*',
        'first_name': 'John',
        'last_name': 'Doe',
        'is_active': True,
    },
    {
        'username': 'jane.doe',
        'email': 'jane.doe@example.com',
        'password': '*',
        'first_name': 'Jane',
        'last_name': 'Doe',
        'is_active': False,
    },
]


def create_users(apps, schema_editor):
    from django.contrib.auth.models import User  # we want methods from User, so we need to import the actual model
    for user in USERS:
        User.objects.create_user(**user)


def delete_users(apps, schema_editor):
    UserModel = apps.get_model('auth', 'User')
    usernames = [user['username'] for user in USERS]
    UserModel.objects.filter(username__in=usernames).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(create_users, delete_users),
    ]
