# Generated by Django 3.0.5 on 2020-05-03 14:48

from django.db import migrations

GROUPS = [
    ('all-users', ('john.doe', 'jane.doe')),
    ('fathers', ('john.doe',)),
    ('mothers', ('jane.doe',)),
    ('empty-group', ()),
]


def create_groups(apps, schema_editor):
    UserModel = apps.get_model('auth', 'User')
    GroupModel = apps.get_model('auth', 'Group')
    for group_name, group_users in GROUPS:
        group = GroupModel.objects.create(name=group_name)
        for user in UserModel.objects.filter(username__in=group_users):
            user.groups.add(group)


def remove_groups(apps, schema_editor):
    GroupModel = apps.get_model('auth', 'Group')
    group_names = [group_name for group_name, _ in GROUPS]
    GroupModel.objects.filter(name__in=group_names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('queries', '0001_initial_data'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups)
    ]
