name: run unit tests
on: push

# based on https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.1
        env:
          POSTGRES_PASSWORD: secretpass
        ports:
        - 5556:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: dschep/install-pipenv-action@v1
    - name: pipenv install
      run: |
        pipenv install

    - name: run tests
      run: |
        DJANGO_SETTINGS_MODULE=querysets.test_settings pipenv run python manage.py test
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        POSTGRES_PASSWORD: secretpass
